formatVersion: 1
formatType: am-configuration
---
applications:
  builtinAppsManifestDir: "${EXECUTABLE_DIR}/apps"
  installationDir: "${stdpath:TempLocation}/qtam-example/application-features/apps"

logging:
  rules:
    - "*=false"
    - "qt.*=false"
    - "am.*=false"
    - "qml*=true"
    - "*.warning=true"
    - "*.critical=true"

ui:
  mainQml: "${CONFIG_DIR}/SystemUi/main.qml"

# development setup:
flags:
  noSecurity: yes
  noUiWatchdog: yes
