#!/bin/sh

USER="$1"
TARGET="$2"
PKGURL="$3"

CONTROLLER=/usr/bin/appman-controller


if [ -z "$USER" ] || [ -z "$TARGET" ] || [ -z "$PKGURL" ]; then
    echo "Usage: `basename $0` <user> <target name/ip> <packagefile>"
    exit 1
fi

cat "$3" | ssh "${USER}@${TARGET}" "$CONTROLLER" -
