qt_commandline_option(force-single-process TYPE enum NAME force_mode VALUE single)
qt_commandline_option(force-multi-process TYPE enum NAME force_mode VALUE multi)
qt_commandline_option(installer TYPE boolean)
qt_commandline_option(external-dbus-interfaces TYPE boolean)
qt_commandline_option(tools-only TYPE boolean)
qt_commandline_option(libbacktrace TYPE boolean)
qt_commandline_option(stackwalker TYPE boolean)
qt_commandline_option(libyaml TYPE enum VALUES qt system)
