formatVersion: 1
formatType: am-configuration
---
applications:
  builtinAppsManifestDir: "${EXECUTABLE_DIR}/apps"


runtimes:
  qml:
    importPaths: "${EXECUTABLE_DIR}/imports"

ui:
  mainQml: "${CONFIG_DIR}/system-ui.qml"
  importPaths: "${EXECUTABLE_DIR}/imports"
  style: Material

# development setup:
flags:
  noSecurity: yes
  noUiWatchdog: yes
  developmentMode: yes
