%YAML 1.2
---
formatVersion: 1
formatType: am-configuration
---
applications:
  builtinAppsManifestDir: "${EXECUTABLE_DIR}/apps"

ui:
  mainQml: "${CONFIG_DIR}/system-ui/main.qml"

flags:
  developmentMode: system
