formatVersion: 1
formatType: am-configuration
---
applications:
  builtinAppsManifestDir: "${EXECUTABLE_DIR}/apps"
  installationDir: "${stdpath:TempLocation}/qtam-example/package-installation/apps"

ui:
  fullscreen: no
  mainQml: "${CONFIG_DIR}/system-ui/main.qml"
  style: Universal

systemProperties:
  public:
    serverBaseDir: '${EXECUTABLE_DIR}/ps-data'
    packageServer:
      url: "http://localhost:8020"
      projectId: 'PROJECT'

# development setup:
flags:
  noSecurity: yes
  noUiWatchdog: yes
