
math(EXPR QT_AM_VERSION
     "(${PROJECT_VERSION_MAJOR} << 16) | (${PROJECT_VERSION_MINOR} << 8) | ${PROJECT_VERSION_PATCH}"
     OUTPUT_FORMAT HEXADECIMAL
)
qt_extra_definition("QT_AM_VERSION" ${QT_AM_VERSION} PUBLIC)
qt_extra_definition("QT_AM_VERSION_STR" "\"${PROJECT_VERSION}\"" PUBLIC)
qt_extra_definition("QT_AM_VERSION_MAJOR" ${PROJECT_VERSION_MAJOR} PUBLIC)
qt_extra_definition("QT_AM_VERSION_MINOR" ${PROJECT_VERSION_MINOR} PUBLIC)
qt_extra_definition("QT_AM_VERSION_PATCH" ${PROJECT_VERSION_PATCH} PUBLIC)
