formatVersion: 1
formatType: am-configuration
---
applications:
  builtinAppsManifestDir: "${EXECUTABLE_DIR}/apps"

ui:
  mainQml: "${CONFIG_DIR}/system-ui.qml"

runtimes:
  qml:
    importPaths: "${EXECUTABLE_DIR}/imports"

quicklaunch:
  runtimesPerContainer:
    bubblewrap:
      qml: 1
    '*': 0

containers:
  bubblewrap:
    sharedNamespaces: [ '-all', '+net' ]
    # You can use this script as a starting point. It has to be adapted to
    # your network setup though:
    # networkSetupScript: 'sudo "${EXECUTABLE_DIR}/bubblewrap-network-setup.sh"'

    # set to yes, if you build against a system or Installer Qt and the launcher cannot be found
    bindMountHome: yes
    configuration:
      symlink:
        usr/lib: '/lib'
        usr/lib64: '/lib64'
        usr/bin: [ '/bin', '/sbin' ]
      ro-bind:
        /usr/bin: '/usr/bin'
        /usr/lib: '/usr/lib'
        /etc: '/etc'
        /usr/share/fonts: '/usr/share/fonts'
        /usr/share/fontconfig: '/usr/share/fontconfig'
        /usr/share/ca-certificates: '/usr/share/ca-certificates'
        /sys/dev/char: '/sys/dev/char'
        ${EXECUTABLE_DIR}/imports: '${EXECUTABLE_DIR}/imports'
      ro-bind-try:
        /usr/lib64: '/usr/lib64'
        '/sys/devices/pci0000:00': '/sys/devices/pci0000:00'
        /usr/share/glvnd/egl_vendor.d: '/usr/share/glvnd/egl_vendor.d'
        /usr/share/X11/xkb: '/usr/share/X11/xkb'
        /run/resolvconf: '/run/resolvconf'
      dev: '/dev'
      dev-bind:
        /dev/dri: '/dev/dri'
      proc:
        /proc

  selection:
    - '*': bubblewrap
